import Navbar from './components/NavBar';
import './globals.css';
import { Nunito } from 'next/font/google';

const nunito = Nunito({
  weight: ['300', '400', '500', '700'],
  style: ['italic', 'normal'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={nunito.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
